# apiVersion: v1
# kind: Namespace
# metadata:
#   name: production

# ---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: www
  # namespace: production
spec:
  replicas: 3
  template:
    metadata:
      labels:
        web: rails
    spec:
      containers:
      - name: todo
        image: chyld/todo:v1
        env:
        - name: DATABASE_PASSWORD
          value: "Postgres12345"
        ports:
        - containerPort: 3333

#---

# apiVersion: v1
# kind: Service
# metadata:
#   name: lb
#   # namespace: production
#   labels:
#     service: loadbalancer
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#     targetPort: 3333
#   selector:
#     web: rails
